"""Chat agent — bilingual (English / Cantonese) follow-up assistant.

Intent detection is deterministic and grounded in the shop's report. When a
real LLM provider is configured the reply is generated by the model using the
report as context; offline, curated bilingual answers keep the demo useful.
"""
from __future__ import annotations

import re

from .base import get_provider

INTENTS = {
    "margin": re.compile(
        r"margin|profit|cost|lose|losing|loss|money|unprofitable|dish|menu|蝕|利|成本|賺|錢",
        re.I,
    ),
    "price": re.compile(r"price|pricing|charge|raise|increase|加價|定價|貴|加价", re.I),
    "waste": re.compile(r"waste|throw|leftover|spoil|浪費|剩|丟|丢", re.I),
    "marketing": re.compile(r"market|promot|insta|post|social|advert|推廣|營銷|宣傳|推广", re.I),
    "score": re.compile(r"score|health|grade|rating|評分|健康|评分", re.I),
}

GREET = re.compile(r"^(hi|hello|hey|你好|哈囉|早晨)\b", re.I)

REPLIES = {
    "en": {
        "greet": "Hi! I'm your Shop Doctor 🩺 I've read your shop's report. Ask me about margins, pricing, waste, marketing or your health score — in English or 廣東話.",
        "margin": "Your thinnest margins are on the beef brisket noodles (~35%) and the two sandwiches (under 20%). They're a big slice of sales but barely profit. Two quick wins: raise brisket noodles toward HK$58, or renegotiate the supplier — worth roughly HK$7k/month.",
        "price": "Use the Price Simulator. On milk tea, HK$26 → HK$28 keeps nearly all volume (it's a habit buy) and adds ~HK$3.7k/month. Signature drinks tolerate small increases better than full meals.",
        "waste": "Weekday waste is ~9% versus 4-5% at surviving twin shops. Batch-prep sandwiches to order after 2pm and cut weekday noodle prep ~30% — about HK$6k/month saved.",
        "marketing": "Push your high-margin heroes: milk tea (69%) and pineapple bun (69%). A weekday 'afternoon tea set' — milk tea + bun for HK$32 — lifts ticket size on your most profitable items. I can draft the Insta posts in the Marketing Kit.",
        "score": "Your Health Score reflects dish margins, rent/labour/COGS ratios and waste, benchmarked against 40+ similar cha chaan tengs. The fastest way to raise it: fix the 2-3 dishes losing money and cut weekday waste.",
        "default": "Good question. Based on your report the biggest lever is dish margin — a few items lose money. Want me to walk through pricing, waste, or marketing?",
    },
    "zh": {
        "greet": "你好！我係你嘅 Shop Doctor 🩺 我睇咗你店舖嘅報告。可以問我利潤、定價、浪費、推廣或者健康評分 — 廣東話或英文都得。",
        "margin": "你利潤最薄嘅係招牌牛腩麵（約35%）同兩款三文治（低過20%）。佢哋佔好多銷售但幾乎唔賺錢。兩個快贏：牛腩麵加到 HK$58，或者同供應商傾平啲 — 每個月多賺約 HK$7,000。",
        "price": "用吓定價模擬器！奶茶由 HK$26 加到 HK$28，客人習慣咗照買，每月多賺約 HK$3,700。招牌飲品比正餐更頂得住小幅加價。",
        "waste": "平日浪費約 9%，生存嘅同類店只有 4-5%。下午兩點後三文治即叫即做，平日麵類備料減三成，預計每月慳約 HK$6,000。",
        "marketing": "主力推你高利潤嘅招牌：奶茶（69%）同菠蘿油（69%）。平日搞個『下午茶套餐』— 奶茶 + 菠蘿油 HK$32，提高最賺錢產品嘅客單價。我可以喺推廣工具度幫你寫好 Instagram 文案。",
        "score": "你嘅健康評分綜合咗菜品利潤、租金/人工/食材比率同浪費，再用 40+ 間同類茶餐廳做基準。最快提升方法：修正 2-3 款蝕錢嘅菜，同埋減少平日浪費。",
        "default": "好問題。根據你嘅報告，最大嘅槓桿係菜品利潤 — 有幾款蝕錢。想我講定價、浪費，定推廣？",
    },
}


def detect_intent(message: str) -> str:
    if GREET.match(message.strip()):
        return "greet"
    for intent, pattern in INTENTS.items():
        if pattern.search(message):
            return intent
    return "default"


def answer(message: str, lang: str = "en", report_context: str | None = None) -> tuple[str, str]:
    """Return (reply, intent)."""
    lang = "zh" if lang.startswith("zh") else "en"
    intent = detect_intent(message)

    provider = get_provider()
    if provider.name != "mock":
        try:
            sys = (
                "You are ShopDoctor, a warm business GP for small Hong Kong restaurants. "
                f"Answer in {'Cantonese (Traditional Chinese)' if lang == 'zh' else 'English'}, "
                "concise and concrete, grounded in the report."
            )
            prompt = f"Report:\n{report_context or '(none)'}\n\nOwner asks: {message}"
            return provider.complete(prompt, system=sys), intent
        except Exception:  # pragma: no cover - network path
            pass

    return REPLIES[lang].get(intent, REPLIES[lang]["default"]), intent
